name: default
version: 1.0.0
config-version: 2
profile: default
model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]
target-path: target
clean-targets: [target, dbt_packages]
models:
  default:
    example: {+materialized: view}
quoting: {identifier: true, schema: true, database: false}
