{{config(
	schema = "DATA_PIPELINE",
	materialized = "table"
)}}
WITH select_step1 as (
  SELECT
    "MASTER_PLAN_TABLE_WDATES"."PLAN_ID" AS "PLAN_ID",
    "MASTER_PLAN_TABLE_WDATES"."PLAN_NAME" AS "PLAN_NAME",
    "MASTER_PLAN_TABLE_WDATES"."MER" AS "MER",
    "MASTER_PLAN_TABLE_WDATES"."DISC" AS "DISC",
    "MASTER_PLAN_TABLE_WDATES"."PACKAGE" AS "PACKAGE",
    "MASTER_PLAN_TABLE_WDATES"."LEN" AS "LEN",
    "MASTER_PLAN_TABLE_WDATES"."ROLLUP1" AS "ROLLUP1",
    "MASTER_PLAN_TABLE_WDATES"."ASP" AS "ASP",
    "MASTER_PLAN_TABLE_WDATES"."STARTDATE" AS "STARTDATE",
    "MASTER_PLAN_TABLE_WDATES"."ENDDATE" AS "ENDDATE"
  FROM
    "SCHEMA_INFO"."MASTER_PLAN_TABLE_WDATES"
)
SELECT
  *
FROM
  select_step1
LIMIT
  100